<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <RootNamespace>Gamem</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>1.3.0</Version>
  <Title>Gamem</Title>
  <Authors>nicky_sus</Authors>
  <Description>This library allows you to use physics and math methods for developing games</Description>
  <PackageReleaseNotes>
    1.3.0 is out!
    Check the full changelog on GitHub!
    https://github.com/nicky-suss/Gamem/releases
  </PackageReleaseNotes>
  <PackageLicenseExpression>MIT</PackageLicenseExpression>
  <GenerateDocumentationFile>true</GenerateDocumentationFile>
  <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  <RepositoryUrl>https://github.com/nicky-suss/Gamem</RepositoryUrl>
    <PackageTags>gamedev;game-development;physics;math;collision;geometry;monogame;godot;unity;utilities;lightweight</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
   <PackageIcon>logo.png</PackageIcon>
  </PropertyGroup>
  <ItemGroup>
  <None Include="README.md" Pack="true" PackagePath="\" />
  <None Include="images\logo.png" Pack="true" PackagePath="\" />
  </ItemGroup>
  
</Project>
