<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net8.0</TargetFrameworks>
    <RootNamespace>Gamem</RootNamespace>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <Version>2.3.1</Version>
    <Title>Gamem</Title>
    <Authors>nicky_sus</Authors>
    <Description>Gamem is a C# library of Physics, Math and Geometry helpers, created for you to type code in one line instead of huge formulas.</Description>
    <PackageReleaseNotes>
      2.3.1 is out!
      Check the full changelog on GitHub!
      https://github.com/nicky-suss/Gamem/releases
    </PackageReleaseNotes>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <RepositoryUrl>https://github.com/nicky-suss/Gamem</RepositoryUrl>
    <PackageTags>gamedev;game-development;physics;math;collision;geometry;monogame;stride;godot;unity;utilities;lightweight</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageIcon>logo.png</PackageIcon>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="**/*.net8.cs" Condition="'$(TargetFramework)' == 'netstandard2.0'" /> 
    <Compile Remove="**/*.netstandard.cs" Condition="'$(TargetFramework)' == 'net8.0'" />
    <None Include="README.md" Pack="true" PackagePath="/" />
    <None Include="images/logo.png" Pack="true" PackagePath="/" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
    <PackageReference Include="System.Numerics.Vectors" Version="4.6.1" />
  </ItemGroup>
</Project>
