<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.1</TargetFrameworks>
    <RootNamespace>Gamem.Unity</RootNamespace>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <Version>1.0.0</Version>
    <Title>Gamem.Unity</Title>
    <Authors>nicky_sus</Authors>
    <Description>Gamem extension for Unity (supports vectors)</Description>
    <PackageReleaseNotes>
      1.0.0 is out!
      Check the full changelog on GitHub!
      https://github.com/nicky-suss/Gamem/releases
    </PackageReleaseNotes>
    <PackageLicenseFile>LICENSE.md</PackageLicenseFile>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <RepositoryUrl>https://github.com/nicky-suss/Gamem</RepositoryUrl>
    <PackageTags>gamedev;game-development;physics;math;collision;geometry;unity;utilities;lightweight</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageIcon>logo.png</PackageIcon>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Gamem" Version="3.1.0" />
    <None Include="README.md" Pack="true" PackagePath="/" />
    <None Include="images/logo.png" Pack="true" PackagePath="/" />
    <None Include="LICENSE.md" Pack="true" PackagePath="$(PackageLicenseFile)" />
    <PackageReference Include="UnityMathematics" Version="1.3.2" PrivateAssets="All" />
  </ItemGroup>
   <ItemGroup Label="Unity">
    <Reference Include="UnityEngine" PrivateAssets="All">
      <HintPath>$(UNITY_ASSEMBLY_PATH)\UnityEngine.dll</HintPath>
    </Reference>
   </ItemGroup>
</Project>
