name: Publish to NuGet

permissions: 
  id-token: write 
  contents: read

on:
  workflow_dispatch:
jobs:
  run-button-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'
      
      - name: Test project
        run: |
          cd Tests/Unit/Csharp
          dotnet test

      - name: Clean solution
        run: dotnet clean

      - name: Build solution
        run: dotnet build -c Release

      - name: Pack NuGet Packages
        run: dotnet pack -c Release --output ./artifacts

      - name: NuGet Login (OIDC)
        id: nuget-login
        uses: NuGet/login@v1
        with:
          user: nicky_sus

      - name: Push to NuGet.org
        run: |
          dotnet nuget push ./artifacts/*.nupkg \
            --source https://api.nuget.org/v3/index.json \
            --api-key ${{ steps.nuget-login.outputs.NUGET_API_KEY }} \
            --skip-duplicate