name: Publish to npm

permissions: 
  id-token: write 
  contents: read

on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Setup Emscripten SDK
        uses: emscripten-core/setup-emsdk@v14
        with:
          version: latest

      - name: Verify emcc installation
        run: emcc --version

      - name: Install dependencies
        working-directory: src/Web
        run: npm ci

      - name: Build
        working-directory: src/Web
        run: npm run build

      - name: Publish to npm
        working-directory: src/Web
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}